services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-webserver:
    image: apache/airflow:2.8.1

    depends_on:
      - postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

      AWS_ACCESS_KEY_ID: "YOUR_ACCESS_KEY"
      AWS_SECRET_ACCESS_KEY: "YOUR_SECRET_KEY"
      AWS_DEFAULT_REGION: "ap-south-1"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

    command: bash -c "airflow db init && airflow webserver"

    ports:
      - "8080:8080"

  airflow-scheduler:
    image: apache/airflow:2.8.1

    depends_on:
      - postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

      AWS_ACCESS_KEY_ID: "AAKIAxxxx"
      AWS_SECRET_ACCESS_KEY: "xxxxx"
      AWS_DEFAULT_REGION: "ap-south-1"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

    command: scheduler